apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  labels:
    app: spring_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring_app
  template:
    metadata:
      labels:
        app: spring_app
    spec:
      containers:
      - name: docker-practice
        image: shiva1415/docker-practice:20250914120343
        ports:
        - containerPort: 9000
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
